plugins { id "com.android.application" }

android {
    namespace "com.azankhan.vidloom"
    compileSdk 34

    defaultConfig {
        applicationId "com.azankhan.vidloom"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
